version: '3.7'
services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio/data:/data
    environment:
      MINIO_ROOT_USER: "ROOTUSER"
      MINIO_ROOT_PASSWORD: "ROOTPASS123"
    command: server /data --console-address ":9001"
